In [2]:

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [3]:
#Read data
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 3s 0us/step


In [5]:
x_train[0].shape

(28, 28)

In [6]:
x_train = x_train / 255.0
x_test = x_test / 255.0

In [7]:
np.unique(y_train, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8),
 array([5923, 6742, 5958, 6131, 5842, 5421, 5918, 6265, 5851, 5949]))

In [8]:
y_train[0]

np.uint8(5)

In [9]:
to_categorical(y_train)[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [10]:
y_train = to_categorical(y_train, num_classes=10)
y_test = to_categorical(y_test, num_classes=10)

In [11]:
model = Sequential([
    tf.keras.layers.Input(shape = x_train[0].shape),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])


In [12]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten (Flatten)               │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 101,770 (397.54 KB)

 Trainable params: 101,770 (397.54 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_split=0.2)

Epoch 1/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9213 - loss: 0.2776 - val_accuracy: 0.9603 - val_loss: 0.1446
Epoch 2/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9629 - loss: 0.1240 - val_accuracy: 0.9682 - val_loss: 0.1093
Epoch 3/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 1s 926us/step - accuracy: 0.9738 - loss: 0.0874 - val_accuracy: 0.9687 - val_loss: 0.1024
Epoch 4/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 1s 862us/step - accuracy: 0.9813 - loss: 0.0636 - val_accuracy: 0.9721 - val_loss: 0.0921
Epoch 5/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 1s 942us/step - accuracy: 0.9846 - loss: 0.0498 - val_accuracy: 0.9697 - val_loss: 0.0987


In [15]:
model.save('mnist_model.keras')

In [16]:
keras_model = load_model('mnist_model.keras')

In [17]:
model.evaluate(x_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - accuracy: 0.9710 - loss: 0.0963


[0.09627828747034073, 0.9710000157356262]

In [18]:
keras_model.evaluate(x_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step - accuracy: 0.9710 - loss: 0.0963


[0.09627828747034073, 0.9710000157356262]